RDKCOM-4449 REFPLTB-2784 : Disable rdk-easymesh-controller in OneWifi builds
Reason for change: While disabling easymesh distro based on Onewifi distro causes below recursive error
ERROR: bb.data_smart.ExpansionError: Failure expanding expression  ${@bb.utils.contains('DISTRO_FEATURES', 'OneWifi', 'easymesh-controller', '', d)} which triggered exception RecursionError: maximum recursion depth exceeded while calling a Python object
To fix it, changed the variable feature
Test Procedure: rdk-easymesh-controller service should not run in Onewifi image
which is tested on Raspberry Pi.
RDK easy mesh controller feature is by default disabled in Comcast platforms.
Risks: Low

Change-Id: I3c72c8ba6ec2203a25a227854c82332e481f5137
Signed-off-by: Ssandhyarani <sirasanagandla.sandhyarani@ltts.com>
(cherry picked from commit 92b3fa937439e98d2ac73afd916ddb96726c4506)