REFPLTB-2784 : Disable rdk-easymesh-controller in OneWifi builds
Reason for change: While disabling easymesh distro based on Onewifi distro causes below recursive error
ERROR: bb.data_smart.ExpansionError: Failure expanding expression  ${@bb.utils.contains('DISTRO_FEATURES', 'OneWifi', 'easymesh-controller', '', d)} which triggered exception RecursionError: maximum recursion depth exceeded while calling a Python object
To fix it, changed the variable feature
Test Procedure: rdk-easymesh-controller service should not run in Onewifi image
Risks: Low

Change-Id: I8cd4df30d6055771362489ac717c6de3cc839269
Signed-off-by: Ssandhyarani <sirasanagandla.sandhyarani@ltts.com>