RDKCOM-4513: RDKBDEV-2349: fix result returned by stub for wifi API's
Reason for change: Build issue observed in commscope xb7 platform, hence Regenerated patch file,
4:12:34 ../git/source/wifi/wifi_hal.c: In function 'wifi_setApDTIMInterval':
14:12:34 ../git/source/wifi/wifi_hal.c:136:68: error: 'mac_addr' undeclared (first use in this function)
14:12:34   136 |     return ipc_wifi_getApAssociatedClientDiagnosticResult(apIndex, mac_addr, dev_conn);
14:12:34       |                                                                    ^~~~~~~~
14:12:34 ../git/source/wifi/wifi_hal.c:136:68: note: each undeclared identifier is reported only once for each function it appears in
14:12:34 ../git/source/wifi/wifi_hal.c:136:78: error: 'dev_conn' undeclared (first use in this function)
14:12:34   136 |     return ipc_wifi_getApAssociatedClientDiagnosticResult(apIndex, mac_addr, dev_conn);
14:12:34       |                                                                              ^~~~~~~~
14:12:34 ../git/source/wifi/wifi_hal.c: In function 'wifi_switchBand':
14:12:34 ../git/source/wifi/wifi_hal.c:181:60: error: 'apIndex' undeclared (first use in this function)
14:12:34   181 |     return ipc_wifi_getApAssociatedDeviceDiagnosticResult3(apIndex, associated_dev_array, output_array_size);
14:12:34       |                                                            ^~~~~~~
14:12:34 ../git/source/wifi/wifi_hal.c:181:69: error: 'associated_dev_array' undeclared (first use in this function)
14:12:34   181 |     return ipc_wifi_getApAssociatedDeviceDiagnosticResult3(apIndex, associated_dev_array, output_array_size);
14:12:34       |                                                                     ^~~~~~~~~~~~~~~~~~~~
14:12:34 ../git/source/wifi/wifi_hal.c:181:91: error: 'output_array_size' undeclared (first use in this function)
14:12:34   181 |     return ipc_wifi_getApAssociatedDeviceDiagnosticResult3(apIndex, associated_dev_array,
Test Procedure: Verify build is successful
Risks: None
Priority: P1
Signed-off-by: SukanyaIlavarasi <sukanya.i@tataelxsi.co.in>

(cherry picked from commit 07af2c96f69e7e90b01f804752dfa9656768658d)
Change-Id: Ib3e7bee728c409dbecd24dcbf13e1cc517172cb7